Siiu 2022
colav/oracle-docker pull request #6
Opened 2022-10-03 20:05 UTC by danielxf007

The folder siiu contains the package which can be used to create an image of Oracle Express and import the DB from SIIU.

2022-10-03 23:11 UTC, omazapa requested changes
Hola Daniel,
muchas gracias por el PR,
el archivo siiu/build/18.4.0/.loadDump.sh.swp se puede borrar.

al cargar el docker-compose me sale 
oracle-docker_1  | /opt/oracle/runOracle.sh: line 220: [5: command not found
oracle-docker_1  | something went wrong while executing loadDump.sh
oracle-docker_1  | cp: omitting directory ‘/tmp/dump/’

2022-10-03 23:11 UTC, omazapa commented on siiu/build/buildContainerImage.sh
> +  IMAGE_NAME="danielxf007/oracle-docker:latest"
Este se tiene que cambiar por colav/siiu-oracle-docker

2022-10-07 16:02 UTC, danielxf007 commented on siiu/build/buildContainerImage.sh
> +  IMAGE_NAME="danielxf007/oracle-docker:latest"
hecho

2022-10-07 16:58 UTC, omazapa commented on siiu/build/18.4.0/Dockerfile.xe
>  LABEL "provider"="danielxf007"                                               \
cuadremos esto también, el provider es Colav
https://github.com/colav/oracle-docker/blob/main/scienti/build/18.4.0/Dockerfile.xe#L35

2022-10-07 17:08 UTC, danielxf007 commented on siiu/build/18.4.0/Dockerfile.xe
>  LABEL "provider"="danielxf007"                                               \
Hecho

2022-10-12 01:07 UTC, merged